In [15]:
#1 Задание

In [1]:
import numpy as np

# Создание случайной матрицы размера 10x10 с числами из диапазона [-3, 3]
np.random.seed(0)  # Для воспроизводимости результатов
matrix = np.random.randint(-3, 4, (10, 10))

# Извлечение минора 4-го порядка (срез 2, 3, 4, 5 строки и 7, 8, 9, 10 столбцы)
minor_matrix = matrix[1:5, 6:10]

# Вычисление определителя минора
minor_determinant = np.linalg.det(minor_matrix)

print("Квадратная матрица 10x10:")
print(matrix)
print("\nМинор 4-го порядка:")
print(minor_matrix)
print(f"\nОпределитель минора: {minor_determinant:.2f}")

Квадратная матрица 10x10:
[[ 1  2 -3  0  0  0 -2  0  2 -1]
 [ 1  3 -3 -3  1 -1 -2  3  3 -3]
 [-2  2 -2  2 -3 -2  1  0 -3  0]
 [ 2  3 -3 -1  0 -3 -2  0  2  0]
 [ 0  3 -3 -2 -2 -2 -3 -1  1  0]
 [ 3  0 -1  1 -1 -3 -3  1  2  2]
 [ 3 -3  1 -2  1 -2 -1 -1 -3 -2]
 [-2 -2 -2  0  3  0  3 -1  0 -3]
 [ 3  0  2  1 -2 -1  1  0  1  3]
 [ 1  1  0  1  1  1 -3  3  1  0]]

Минор 4-го порядка:
[[-2  3  3 -3]
 [ 1  0 -3  0]
 [-2  0  2  0]
 [-3 -1  1  0]]

Определитель минора: -12.00


# 2

In [2]:
import numpy as np

# Создание двух случайных матриц A и B размером 3x3 с числами из интервала (2, 3)
np.random.seed(1)  # Для воспроизводимости
A = np.random.uniform(2, 3, (3, 3))
B = np.random.uniform(2, 3, (3, 3))

# --- 1. Векторный алгоритм умножения матриц ---
def matrix_multiply_vector(A, B):
    # Размеры матриц A и B
    rows_A, cols_A = A.shape
    rows_B, cols_B = B.shape
    assert cols_A == rows_B, "Число столбцов A должно совпадать с числом строк B"
    
    # Создаем результирующую матрицу C
    C = np.zeros((rows_A, cols_B))
    
    # Векторное произведение (поэлементное сложение произведений строк и столбцов)
    for i in range(rows_A):
        for j in range(cols_B):
            C[i, j] = np.dot(A[i, :], B[:, j])
    return C

C_vector = matrix_multiply_vector(A, B)

# --- 2. Матричный алгоритм (по столбцам матрицы C) ---
def matrix_multiply_by_columns(A, B):
    # Размеры матриц A и B
    rows_A, cols_A = A.shape
    rows_B, cols_B = B.shape
    assert cols_A == rows_B, "Число столбцов A должно совпадать с числом строк B"
    
    # Создаем результирующую матрицу C
    C = np.zeros((rows_A, cols_B))
    
    # Произведение по столбцам B и строкам A
    for j in range(cols_B):
        C[:, j] = np.dot(A, B[:, j])
    return C

C_columns = matrix_multiply_by_columns(A, B)

# --- 3. Умножение с помощью функции np.dot ---
C_dot = np.dot(A, B)

# Вывод результатов
print("Матрица A:")
print(A)
print("\nМатрица B:")
print(B)
print("\nПроизведение (векторный алгоритм):")
print(C_vector)
print("\nПроизведение (матричный алгоритм по столбцам):")
print(C_columns)
print("\nПроизведение (np.dot):")
print(C_dot)

# Проверка совпадения результатов
assert np.allclose(C_vector, C_columns), "Результаты векторного и матричного алгоритмов не совпадают!"
assert np.allclose(C_vector, C_dot), "Результаты векторного алгоритма и np.dot не совпадают!"

Матрица A:
[[2.417022   2.72032449 2.00011437]
 [2.30233257 2.14675589 2.09233859]
 [2.18626021 2.34556073 2.39676747]]

Матрица B:
[[2.53881673 2.41919451 2.6852195 ]
 [2.20445225 2.87811744 2.02738759]
 [2.67046751 2.4173048  2.55868983]]

Произведение (векторный алгоритм):
[[17.47444182 18.51154582 17.12305905]
 [16.16514355 16.80622602 15.88822006]
 [17.1216803  17.83350546 16.75853383]]

Произведение (матричный алгоритм по столбцам):
[[17.47444182 18.51154582 17.12305905]
 [16.16514355 16.80622602 15.88822006]
 [17.1216803  17.83350546 16.75853383]]

Произведение (np.dot):
[[17.47444182 18.51154582 17.12305905]
 [16.16514355 16.80622602 15.88822006]
 [17.1216803  17.83350546 16.75853383]]


# 3

In [3]:
import numpy as np

# Создание случайного вектора-строки 1x10 из целых чисел
np.random.seed(2)  # Для воспроизводимости
x = np.random.randint(-10, 10, 10)

# Функция для вычисления нормы ||x||_1
def norm_1(x):
    return np.sum(np.abs(x))

# Вычисление нормы с помощью собственной функции
norm_1_custom = norm_1(x)

# Проверка с помощью функции linalg.norm
norm_1_linalg = np.linalg.norm(x, 1)

# Вывод результатов
print("Вектор-строка x:")
print(x)
print(f"\nНорма ||x||_1 (собственная функция): {norm_1_custom}")
print(f"\nНорма ||x||_1 (linalg.norm): {norm_1_linalg}")

Вектор-строка x:
[-2  5  3 -2  1  8  1 -2 -3 -8]

Норма ||x||_1 (собственная функция): 35

Норма ||x||_1 (linalg.norm): 35.0


# 4

In [23]:
import numpy as np

# Создание случайной матрицы размером 5x5 из целых чисел
np.random.seed(3)  # Для воспроизводимости
matrix = np.random.randint(-10, 10, (5, 5))

# Функция для нахождения спектральной нормы матрицы
def spectral_norm(matrix):
    # Находим собственные значения матрицы
    eigenvalues = np.linalg.eigvals(matrix)
    # Спектральная норма равна максимальному модулю собственных значений
    return np.max(np.abs(eigenvalues))

# Вычисление спектральной нормы с помощью собственной функции
spectral_norm_custom = spectral_norm(matrix)

# Проверка с помощью функции linalg.norm
spectral_norm_linalg = np.linalg.norm(matrix, ord=2)

# Вывод результатов
print("Случайная матрица:")
print(matrix)
print(f"\nСпектральная норма (собственная функция): {spectral_norm_custom}")
print(f"Спектральная норма (linalg.norm): {spectral_norm_linalg}")

Случайная матрица:
[[  0  -7  -2 -10   9]
 [  0   1  -1   0  -4]
 [-10   2  -3   4   7]
 [ -8  -8  -9   9  -5]
 [ -2   4  -9   0  -3]]

Спектральная норма (собственная функция): 12.23606942666398
Спектральная норма (linalg.norm): 20.250499945196683


# 5

In [24]:
import numpy as np

# Вектор из третьего пункта
x = np.random.randint(-10, 10, 10)

# Функция для вычисления отражения Хаусхолдера
def householder_reflection(x):
    # Извлекаем нужные координаты
    v = x[3:]  # координаты с 4 по 10
    norm_v = np.linalg.norm(v)
    
    # Определяем с коэффициентом c для отражения
    if norm_v == 0:
        return x  # Если вектор нулевой, возвращаем его без изменений

    # Составляем вектор u
    u = v.copy()
    u[0] += np.sign(v[0]) * norm_v  # добавляем знак к первому элементу
    
    # Нормируем вектор u
    u_norm = np.linalg.norm(u)
    
    # Создаем матрицу отражения H
    # Размерность матрицы отражения должна быть той же, что и размерность вектора
    I = np.eye(len(x))
    
    # Составляем вектор для отражения
    H = I - (2 / (u_norm ** 2)) * np.outer(u, u)
    
    # Применяем отражение к вектору
    return H @ x

# Применение отражения Хаусхолдера
x_reflected = householder_reflection(x)

# Вывод результатов
print("Исходный вектор x:")
print(x)
print("\nВектор после отражения Хаусхолдера:")
print(x_reflected)

ValueError: operands could not be broadcast together with shapes (10,10) (7,7) 

# 6

In [25]:
import numpy as np

# Создание случайной матрицы размером 5x5 из целых чисел
np.random.seed(4)  # Для воспроизводимости
matrix = np.random.randint(-10, 10, (5, 5))

# Функция для LU разложения
def lu_decomposition(matrix):
    n = matrix.shape[0]
    L = np.zeros((n, n))
    U = np.zeros((n, n))

    for i in range(n):
        # U формируется по строкам
        for j in range(i, n):
            U[i, j] = matrix[i, j] - np.sum(L[i, :i] * U[:i, j])

        # L формируется по столбцам
        for j in range(i, n):
            if U[i, i] == 0:
                raise ValueError("Матрица является вырожденной.")
            L[j, i] = (matrix[j, i] - np.sum(L[j, :i] * U[:i, i])) / U[i, i]

        L[i, i] = 1  # диагональные элементы L равны 1

    return L, U

# Применение LU разложения
L, U = lu_decomposition(matrix)

# Проверка результата перемножением матриц L и U
LU_product = L @ U

# Вывод результатов
print("Исходная матрица:")
print(matrix)
print("\nМатрица L:")
print(L)
print("\nМатрица U:")
print(U)
print("\nПроверка (L @ U):")
print(LU_product)

Исходная матрица:
[[  4  -5  -9  -2  -2]
 [  8  -1  -3   3  -2]
 [ -6   8   2  -4   0]
 [ -7 -10  -1  -4  -4]
 [ -8   4  -2   7  -8]]

Матрица L:
[[ 1.          0.          0.          0.          0.        ]
 [ 2.          1.          0.          0.          0.        ]
 [-1.5         0.05555556  1.          0.          0.        ]
 [-1.75       -2.08333333 -1.17567568  1.          0.        ]
 [-2.         -0.66666667  0.81081081 -8.51685393  1.        ]]

Матрица U:
[[  4.          -5.          -9.          -2.          -2.        ]
 [  0.           9.          15.           7.           2.        ]
 [  0.           0.         -12.33333333  -7.38888889  -3.11111111]
 [  0.           0.           0.          -1.6036036   -6.99099099]
 [  0.           0.           0.           0.         -67.68539326]]

Проверка (L @ U):
[[  4.  -5.  -9.  -2.  -2.]
 [  8.  -1.  -3.   3.  -2.]
 [ -6.   8.   2.  -4.   0.]
 [ -7. -10.  -1.  -4.  -4.]
 [ -8.   4.  -2.   7.  -8.]]


# 7