# 1 Задание

In [2]:
import numpy as np

# Задание произвольной верхнетреугольной матрицы порядка 5
A = np.array([
    [2, -1, 3, 5, 7],
    [0, 4, -2, 8, 9],
    [0, 0, 5, -3, 1],
    [0, 0, 0, 6, 4],
    [0, 0, 0, 0, 3]
])

# Произвольный вектор B
B = np.array([5, 7, -2, 4, 6])


# Функция для решения системы методом обратной подстановки
def back_substitution(A, B):
    n = len(B)
    X = np.zeros_like(B, dtype=np.float64)

    for i in range(n - 1, -1, -1):  # Обратная итерация по строкам
        X[i] = (B[i] - np.dot(A[i, i + 1:], X[i + 1:])) / A[i, i]

    return X


# Решение системы методом обратной подстановки
X_back_substitution = back_substitution(A, B)

# Проверка решения с помощью функции np.linalg.solve
X_np_solve = np.linalg.solve(A, B)

# Вывод результатов
print("Матрица A:")
print(A)
print("\nВектор B:")
print(B)
print("\nРешение методом обратной подстановки:")
print(X_back_substitution)
print("\nРешение с помощью np.linalg.solve:")
print(X_np_solve)

Матрица A:
[[ 2 -1  3  5  7]
 [ 0  4 -2  8  9]
 [ 0  0  5 -3  1]
 [ 0  0  0  6  4]
 [ 0  0  0  0  3]]

Вектор B:
[ 5  7 -2  4  6]

Решение методом обратной подстановки:
[-2.04166667 -2.01666667 -1.2        -0.66666667  2.        ]

Решение с помощью np.linalg.solve:
[-2.04166667 -2.01666667 -1.2        -0.66666667  2.        ]


# 2 Задание

In [4]:
import numpy as np
from scipy.linalg import lu

# Матрица коэффициентов A и вектор B
A = np.array([
    [4.4, -2.5, 19.2, -10.8],
    [5.5, -9.3, -14.2, 13.2],
    [7.1, -11.5, 5.3, -6.7],
    [14.2, 23.4, -8.8, 5.3]
])

B = np.array([4.3, 6.8, -1.8, 7.2])

# LU разложение
P, L, U = lu(A)

# Прямой ход: решение LY = P*B
Y = np.linalg.solve(L, np.dot(P, B))

# Обратный ход: решение UX = Y
X = np.linalg.solve(U, Y)

# Вывод результатов
print("Матрица A:")
print(A)
print("\nВектор B:")
print(B)
print("\nРешение системы X:")
print(X)

Матрица A:
[[  4.4  -2.5  19.2 -10.8]
 [  5.5  -9.3 -14.2  13.2]
 [  7.1 -11.5   5.3  -6.7]
 [ 14.2  23.4  -8.8   5.3]]

Вектор B:
[ 4.3  6.8 -1.8  7.2]

Решение системы X:
[0.44483668 0.06731407 0.86853494 1.31156176]


# 3 

In [5]:
import numpy as np

# Матрица A и вектор B из системы уравнений
A = np.array([
    [4.4, -2.5, 19.2, -10.8],
    [5.5, -9.3, -14.2, 13.2],
    [7.1, -11.5, 5.3, -6.7],
    [14.2, 23.4, -8.8, 5.3]
])

B = np.array([4.3, 6.8, -1.8, 7.2])

# Функция для вычисления QR-разложения методом Хаусхолдера
def qr_householder(A):
    m, n = A.shape
    Q = np.eye(m)
    R = A.copy()
    
    for i in range(n):
        # Вектор для отражения Хаусхолдера
        x = R[i:, i]
        e = np.zeros_like(x)
        e[0] = np.linalg.norm(x)
        
        u = x - e
        v = u / np.linalg.norm(u)
        
        # Построение матрицы Хаусхолдера
        Q_i = np.eye(m)
        Q_i[i:, i:] -= 2.0 * np.outer(v, v)
        
        # Обновление матриц Q и R
        R = Q_i @ R
        Q = Q @ Q_i
    
    return Q, R

# Найдем QR разложение
Q, R = qr_householder(A)

# Решение системы через QR разложение: R * X = Q.T * B
Y = np.dot(Q.T, B)
X_qr = np.linalg.solve(R, Y)

# Проверка решения с помощью np.linalg.solve
X_np_solve = np.linalg.solve(A, B)

# Проверка решения непосредственной подстановкой
B_check = np.dot(A, X_qr)

# Вывод результатов
print("Матрица A:")
print(A)
print("\nВектор B:")
print(B)
print("\nQR разложение методом Хаусхолдера:")
print("Матрица Q:")
print(Q)
print("\nМатрица R:")
print(R)
print("\nРешение системы X (QR разложение):")
print(X_qr)
print("\nРешение системы X (np.linalg.solve):")
print(X_np_solve)
print("\nПроверка решения (Ax = B):")
print(B_check)

Матрица A:
[[  4.4  -2.5  19.2 -10.8]
 [  5.5  -9.3 -14.2  13.2]
 [  7.1 -11.5   5.3  -6.7]
 [ 14.2  23.4  -8.8   5.3]]

Вектор B:
[ 4.3  6.8 -1.8  7.2]

QR разложение методом Хаусхолдера:
Матрица Q:
[[ 0.25333419 -0.20513523  0.77135795  0.54657867]
 [ 0.31666774 -0.49773569 -0.61068324  0.52824871]
 [ 0.40878927 -0.62277856  0.15917782 -0.64784306]
 [ 0.81757854  0.56773726 -0.08206899 -0.05004425]]

Матрица R:
[[ 1.73683620e+01  1.08519157e+01 -4.66077341e+00  3.03828305e+00]
 [-2.34935093e-16  2.55887852e+01 -5.16756380e+00  2.82697315e+00]
 [-3.62716189e-15 -1.12485789e-15  2.50476241e+01 -1.78931417e+01]
 [-1.18050600e-15  1.16825357e-15 -3.45566339e-15  5.14514729e+00]]

Решение системы X (QR разложение):
[0.44483668 0.06731407 0.86853494 1.31156176]

Решение системы X (np.linalg.solve):
[0.44483668 0.06731407 0.86853494 1.31156176]

Проверка решения (Ax = B):
[ 4.3  6.8 -1.8  7.2]


# 4

In [14]:
import numpy as np
import pandas as pd

# Исходная матрица A и вектор B
A = np.array([
    [2.7, 3.3, 1.3],
    [3.5, -1.7, 2.8],
    [4.1, 5.8, -1.7]
])

B = np.array([2.1, 1.7, 0.8])

# Преобразование системы к диагонально доминирующему виду
def make_diag_dominant(A, B):
    # Попробуем переставить строки, чтобы сделать диагональ доминирующей
    A_transformed = np.array([
        # Переставляем первую строку на последнюю позицию
        [2.7, 3.3, 1.3],
        [3.5, -1.7, 2.8],
        [4.1, 5.8, -1.7],
        
    ])
    B_transformed = np.array([0.8, 1.7, 2.1])
    return A_transformed, B_transformed

A_transformed, B_transformed = make_diag_dominant(A, B)

# Спектральный радиус (максимальное собственное значение матрицы итерационного процесса)
def spectral_radius(A):
    D = np.diag(np.diag(A))  # Диагональная матрица
    L = np.tril(A, -1)  # Нижняя треугольная матрица
    U = np.triu(A, 1)   # Верхняя треугольная матрица
    
    # Матрица итераций
    T = np.dot(np.linalg.inv(D), -(L + U))
    
    # Собственные значения
    eigenvalues = np.linalg.eigvals(T)
    
    # Спектральный радиус
    return max(abs(eigenvalues))

rho = spectral_radius(A_transformed)

# Если спектральный радиус < 1, можно применять метод простых итераций
if rho < 1:
    print(f"Система пригодна для итераций, спектральный радиус: {rho:.4f}")
else:
    print(f"Спектральный радиус = {rho:.4f} > 1. Система не сойдётся без преобразований.")

# Итерационный метод
def iteration_method(A, B, epsilon=1e-3, max_iter=100):
    n = len(B)
    x = np.zeros(n)  # Начальное приближение
    iterations = []

    for iteration in range(max_iter):
        x_new = np.zeros(n)
        
        # Метод простых итераций
        for i in range(n):
            sum1 = sum(A[i][j] * x[j] for j in range(n) if j != i)
            x_new[i] = (B[i] - sum1) / A[i][i]
        
        iterations.append([iteration + 1] + list(x_new))
        
        # Условие остановки по норме разности
        if np.linalg.norm(x_new - x, ord=np.inf) < epsilon:
            break
        
        x = x_new
    
    return np.array(iterations), x_new

# Выполнение метода итераций
iterations, solution = iteration_method(A_transformed, B_transformed)

# Таблица итераций
iterations_table = pd.DataFrame(iterations, columns=["Iteration", "x1", "x2", "x3"])

# Проверка решения
check_solution = np.allclose(np.dot(A_transformed, solution), B_transformed)

# Вывод результатов
print("Таблица итераций:")
print(iterations_table)
print("\nПолученное решение:", solution)
print("Проверка решения (A @ x = B):", check_solution)


Спектральный радиус = 2.3378 > 1. Система не сойдётся без преобразований.
Таблица итераций:
    Iteration            x1            x2            x3
0         1.0  2.962963e-01 -1.000000e+00 -1.235294e+00
1         2.0  2.113290e+00 -2.424580e+00 -3.932462e+00
2         3.0  5.153080e+00 -3.126105e+00 -4.410634e+00
3         4.0  6.240730e+00  2.344708e+00  5.271859e-01
4         5.0 -2.823289e+00  1.271687e+01  2.181547e+01
..        ...           ...           ...           ...
95       96.0  8.643279e+32  4.715515e+33 -7.773485e+33
96       97.0 -2.020618e+33 -1.102389e+34  1.817278e+34
97       98.0  4.723782e+33  2.577155e+34 -4.248417e+34
98       99.0 -1.104322e+34 -6.024849e+34  9.931911e+34
99      100.0  2.581673e+34  1.408484e+35 -2.321873e+35

[100 rows x 4 columns]

Полученное решение: [ 2.58167337e+34  1.40848375e+35 -2.32187314e+35]
Проверка решения (A @ x = B): False


In [8]:
import numpy as np

# Матрица коэффициентов A и вектор свободных членов B
A = np.array([
    [4.4, -2.5, 19.2, -10.8],
    [5.5, -9.3, -14.2, 13.2],
    [7.1, -11.5, 5.3, -6.7],
    [14.2, 23.4, -8.8, 5.3],
    [8.2, -3.2, 14.2, 14.8]
])

B = np.array([4.3, 6.8, -1.8, 7.2, -8.4])

# Нахождение псевдорешения методом наименьших квадратов
pseudo_solution, residuals, rank, s = np.linalg.lstsq(A, B, rcond=None)

# Проверка решения (умножение A на найденное псевдорешение)
check_solution = np.dot(A, pseudo_solution)

# Вывод результатов
print("Матрица A:")
print(A)
print("\nВектор B:")
print(B)
print("\nПсевдорешение системы:")
print(pseudo_solution)
print("\nПроверка решения (A @ псевдорешение):")
print(check_solution)
print("\nНевязка (разница между A @ псевдорешение и B):")
print(B - check_solution)

Матрица A:
[[  4.4  -2.5  19.2 -10.8]
 [  5.5  -9.3 -14.2  13.2]
 [  7.1 -11.5   5.3  -6.7]
 [ 14.2  23.4  -8.8   5.3]
 [  8.2  -3.2  14.2  14.8]]

Вектор B:
[ 4.3  6.8 -1.8  7.2 -8.4]

Псевдорешение системы:
[ 0.38466722  0.02588808 -0.34336072 -0.32744471]

Проверка решения (A @ псевдорешение):
[-1.42830728  2.42836258  2.80749217  7.35417287 -6.65047456]

Невязка (разница между A @ псевдорешение и B):
[ 5.72830728  4.37163742 -4.60749217 -0.15417287 -1.74952544]
