# 1 задание

In [5]:
import numpy as np

# Значения переменных
alpha = 7
beta = 3
gamma = 1
mu = 0
nu = 5

# Определим матрицы с подстановкой значений
A = np.array([
    [2, 3 + alpha, 4 - mu],
    [beta, gamma, nu],
    [5, 10 * mu, -2]
])

B = np.array([
    [beta, -3, 4 + mu],
    [alpha, 4, nu],
    [5 * mu, 10, -2]
])

C = np.array([
    [-1, 3 + mu, 4 - nu],
    [2, 1, nu],
    [5, 5 - mu, -2]
])

# Перемножение матриц A, B и C
result = np.matmul(np.matmul(A, B), C)
result


array([[ 322,  552,  194],
       [ 109,  128,  195],
       [  35,  130, -238]])

# Задание 2. Вычислить определитель.

In [6]:
from scipy import linalg

# Определим матрицу G с подстановкой значений
G = np.array([
    [2, 3 + alpha, 4 + mu, 6],
    [beta + 1, gamma, nu, 12],
    [5, -2, 16, mu + 1],
    [2, 7, 11, -6]
])

# Определитель матрицы
determinant = linalg.det(G)

# Собственные значения
eigenvalues, _ = linalg.eig(G)

# Обратная матрица
inverse_G = linalg.inv(G)

determinant, eigenvalues, inverse_G


(np.float64(703.9999999999999),
 array([ 19.91795019+0.j, -13.07510175+0.j,  -0.41153288+0.j,
          6.56868444+0.j]),
 array([[-2.47159091,  2.69034091, -1.99431818,  2.57670455],
        [-0.01136364,  0.07386364, -0.10227273,  0.11931818],
        [ 0.73863636, -0.80113636,  0.64772727, -0.75568182],
        [ 0.51704545, -0.48579545,  0.40340909, -0.55397727]]))

# Задание 3. Найти матрицу Б

In [7]:
# Определим матрицы A и C
A = np.array([
    [2, -5, 7],
    [8, 1, 9],
    [3, -4, 12]
])

C = np.array([
    [-25, -17, 78],
    [11, 89, 76],
    [-5, 24, 115]
])

# Находим обратную матрицу A
A_inv = linalg.inv(A)

# Находим матрицу B
B = np.matmul(A_inv, C)
B


array([[-3.,  4.,  1.],
       [ 8., 12., -4.],
       [ 3.,  5.,  8.]])

# Задание 4. Система линейных уравнений.

In [8]:
# Коэффициенты переменных
A_system = np.array([
    [3, 1, 1, gamma],
    [1, -nu, nu, 4],
    [-5, 0, -1, -7],
    [1, -6, alpha, 6]
])

# Вектор правых частей уравнений
b_system = np.array([alpha, beta, -5, 3])

# Решение системы линейных уравнений
X_solution = linalg.solve(A_system, b_system)
X_solution


array([ 2.26666667,  0.13333333,  1.13333333, -1.06666667])