1

In [3]:
import cvxopt
from scipy.optimize import linprog
import time

# Коэффициенты целевой функции (прибыль)
c = [-6, -8]  # Мы минимизируем, поэтому коэффициенты отрицательные

# Коэффициенты ограничений
A = [
    [2, 4],
    [0.5, 3],
    [2, 0],
    [1, 5]
]
b = [20, 17, 10, 19]

# Решение с помощью scipy
start_scipy = time.time()
result_scipy = linprog(c, A_ub=A, b_ub=b, bounds=(0, None), method='highs')
end_scipy = time.time()

# Решение с помощью cvxopt
from cvxopt import matrix, solvers

# Преобразуем коэффициенты для cvxopt
c_cvxopt = matrix([6.0, 8.0])
G_cvxopt = matrix([[-2.0, -0.5, -2.0, -1.0], [-4.0, -3.0, 0.0, -5.0]])  # Ограничения
b_cvxopt = matrix([-20.0, -17.0, -10.0, -19.0])

start_cvxopt = time.time()
sol_cvxopt = solvers.lp(c_cvxopt, G_cvxopt, b_cvxopt)
end_cvxopt = time.time()

# Время выполнения
scipy_time = end_scipy - start_scipy
cvxopt_time = end_cvxopt - start_cvxopt

print(scipy_time, cvxopt_time)

     pcost       dcost       gap    pres   dres   k/t
 0:  5.2178e+01  5.2178e+01  2e+01  4e-01  1e-16  1e+00
 1:  6.5782e+01  6.7161e+01  3e+01  4e-01  2e-16  2e+00
 2:  6.8323e+01  6.8374e+01  7e-01  8e-03  3e-16  8e-02
 3:  6.8663e+01  6.8664e+01  7e-03  9e-05  0e+00  8e-04
 4:  6.8667e+01  6.8667e+01  7e-05  9e-07  2e-16  8e-06
 5:  6.8667e+01  6.8667e+01  7e-07  9e-09  2e-16  8e-08
Optimal solution found.
0.0012350082397460938 0.007912874221801758


In [6]:
import numpy as np
from scipy.optimize import linprog

# Данные задачи
c = np.array([70, 100, 40, 80, 50,
              90, 50, 120, 60, 70,
              40, 80, 30, 90, 60])  # Стоимость перевозки

# Условия задачи
a = np.array([70, 80, 90])  # Поставщики
b = np.array([20, 60, 70, 50, 40])  # Потребители

# Определяем размерность
m = len(a)  # Количество поставщиков
n = len(b)  # Количество потребителей

# Матрица ограничений
A_eq = np.zeros((m + n, m * n))

# Ограничения по поставщикам
for i in range(m):
    for j in range(n):
        A_eq[i, i * n + j] = 1

# Ограничения по потребителям
for j in range(n):
    for i in range(m):
        A_eq[m + j, i * n + j] = 1

# Векторы правой части ограничений
b_eq = np.concatenate([a, b])

# Решение задачи линейного программирования
result = linprog(c, A_eq=A_eq, b_eq=b_eq, method='highs')

# Вывод результатов
if result.success:
    print("Оптимальное решение:")
    print(result.x.reshape((m, n)))  # Переформатирование результата в матрицу
    print("Минимальная стоимость:", result.fun)
    print(result)
else:
    print("Не удалось найти решение.")


Оптимальное решение:
[[ 0.  0. -0. 30. 40.]
 [ 0. 60.  0. 20.  0.]
 [20.  0. 70.  0.  0.]]
Минимальная стоимость: 11500.0
        message: Optimization terminated successfully. (HiGHS Status 7: Optimal)
        success: True
         status: 0
            fun: 11500.0
              x: [ 0.000e+00  0.000e+00 ...  0.000e+00  0.000e+00]
            nit: 10
          lower:  residual: [ 0.000e+00  0.000e+00 ...  0.000e+00
                              0.000e+00]
                 marginals: [ 2.000e+01  3.000e+01 ...  2.000e+01
                              2.000e+01]
          upper:  residual: [       inf        inf ...        inf
                                    inf]
                 marginals: [ 0.000e+00  0.000e+00 ...  0.000e+00
                              0.000e+00]
          eqlin:  residual: [ 0.000e+00  0.000e+00  0.000e+00  0.000e+00
                              0.000e+00  0.000e+00  0.000e+00  0.000e+00]
                 marginals: [ 1.000e+01 -1.000e+01 -0.000e+00  4.000e